repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-docstring-first
    - id: requirements-txt-fixer
    - id: check-yaml
      additional_dependencies: ['flake8-docstrings', 'darglint']

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4
    hooks:
    - id: autopep8

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.6.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]

-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push]
