# This workflow triggers tests on PRs that targets master branch
name: Python application

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
        # Check Black code style compliance
        black ./ --skip-string-normalization --check

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: pre-commit
      uses: pre-commit/action@v1.0.1

    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.3.0
      if: matrix.py_ver == '3.7'
      env:
        CC_TEST_REPORTER_ID: 8f6ebf829bd7be944b7e16988238ead24ac15f727ceb5a80602bfe8577f4d091
      with:
        coverageCommand: coverage xml
